### ISSUE TITLE
Enhance UI for "Back to Top" Button

### ISSUE THREAD

**Issue by HarshitSharma4** [WebSorcery/jira-wizard#10]
The current UI for the "Back to Top" button could be enhanced to improve user experience and visual appeal.

![Screenshot from 2023-12-10 18-39-42](https://github.com/WebSorcery/jira-wizard/assets/106171546/244e5fc1-0715-4aa1-bbaa-6b6ac33dcea4)

**Comment by ank1traj** [comment]
Fixed by @HarshitSharma4 in PR #12
